#!/bin/sh

### BEGIN INIT INFO
# Provides:             soma
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Enterprise Resource Management software
# Description:          Open ERP is a complete ERP and CRM software.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/soma/odoo/odoo-bin
NAME=soma
DESC="SOMA BY MUTUALIZO"
CONFIG=/opt/soma/init/soma.conf
LOGFILE=/opt/soma/log/soma.log
USER=soma
PIDFILE=/var/run/${NAME}.pid

test -x ${DAEMON} || exit 0

set -e

checkpid() {
  [ -f $PIDFILE ] || return 1
  pid=`cat $PIDFILE`
  [ -d /proc/$pid ] && return 0
  return 1
}

do_start () {
    echo -n "Starting ${DESC} "

    start-stop-daemon --start --pidfile $PIDFILE --chuid ${USER} --background \
    --make-pidfile --exec ${DAEMON} -- --config=${CONFIG} --logfile=${LOGFILE}

    echo "${NAME}."
}

do_stop () {
    echo -n "Stopping ${DESC}: "
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo

    echo "${NAME}."
}

do_status() {

  echo -n "Checking $NAME: "

  checkpid

  if [ $? -eq 1 ]; then
    echo "stopped."
  else
    echo "running."
  fi

}

# Main
case "${1}" in
    start)
        do_start
        ;;

    stop)
        do_stop
        ;;

    restart|force-reload)
        echo -n "Restarting ${DESC}: "
        do_stop
        sleep 1
        do_start
        ;;

    status)
        do_status
        ;;

    *)
        N=/etc/init.d/${NAME}
        echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0